services:
  client:
    image: node:22
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    container_name: eu-tm-app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    container_name: eu-tm-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
